"""
Basic settings of resotool

This file is auto generated by Django
"""

from django.apps import AppConfig


class ResotoolConfig(AppConfig):  # pylint: disable=missing-docstring
    name = "resotool"
