# Generated by Django 2.2.2 on 2019-09-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='postal_adress',
            new_name='postal_address',
        ),
    ]
