# Generated by Django 2.2.2 on 2019-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoapp', '0002_auto_20190727_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='pdf_path',
            field=models.FilePathField(default=''),
        ),
    ]
