# Generated by Django 2.2.2 on 2019-07-27 14:57

from django.db import migrations, models
import resoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('resoapp', '0003_auto_20190727_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='reso_type',
            field=models.IntegerField(choices=[(1, 'resolution'), (2, 'positionspapier'), (4, 'selbstverpflichtung')], default=resoapp.models.ResoType(1)),
        ),
        migrations.AlterField(
            model_name='resolutionemail',
            name='status',
            field=models.IntegerField(choices=[(1, 'success'), (2, 'failure'), (4, 'in progress'), (8, 'not sent')]),
        ),
    ]
