"""
Basic settings of resoapp

This file is auto generated by Django
"""

from django.apps import AppConfig


class ResoappConfig(AppConfig):  # pylint: disable=missing-docstring
    name = "resoapp"
